name: Publish Library

on:
  push:
    branches:
      - main
    paths:
      - 'projects/pa-lib/package.json'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: build library
        run: |
          npx ng build

      - name: Publish to NPM
        run: |
          cd dist/pa-lib
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
