name: Publish Library

on:
  push:
    branches:
      - main
    paths:
      - 'projects/pa-lib/package.json'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create .npmrc file
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - name: Install dependencies
        run: npm install

      - name: build library
        run: |
          npx ng build

      - name: Publish to NPM
        run: |
          cd dist/pa-lib
          npm publish
          cd ../../
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Clean up .npmrc
        if: always()
        run: rm -f .npmrc
