name: Publish Library

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Git set up
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Install dependencies
        run: npm install

      - name: Update version and build library
        run: |
          cd projects/pa-lib
          npm version patch
          git add package.json
          git commit -m "update package.json"
          cd ../../
          npx ng build

      - name: Publish to NPM
        run: |
          cd dist/pa-lib
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
